name: CI/CD Docker Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t myusername/my-app:${{ github.sha }} .

      - name: Run tests inside container
        run: |
          docker run --rm myusername/my-app:${{ github.sha }} python -m unittest discover -s tests

      - name: Push Docker image to Docker Hub
        run: |
          docker push myusername/my-app:${{ github.sha }}

      - name: Run the Docker image locally and check if app is up
        run: |
          docker run -d -p 5000:5000 myusername/my-app:${{ github.sha }}
          sleep 5
          curl http://localhost:5000
        continue-on-error: true 
